### ISSUE TITLE
Interlaced scaling is broken

### ISSUE THREAD

**Issue by premultiply** [jaskie/Server#1]
When scaling interlaced content just one field is used for deinterlacing leading to very poor resolution on static picture parts (fonts, edges etc.) while upscaling SD content for example.

SVT builds are using proper adaptive field/frame deinterlacing.

**Comment by jaskie** [comment]
Can you provide me with configuration and steps to reproduce this behavior? It can be observed while decoding a file, encoding a stream or yet another case?

**Comment by premultiply** [comment]
It can be reproduced by playing SD clip on HD 1080i5000 decklink channel.
Just take a clip with static text or logo content with diagonal edges over video and compare the result to the SVT builds.

**Comment by jaskie** [comment]
With which specific SVT's build (2.0.6 or 2.0.7...) your comparison is?

**Comment by premultiply** [comment]
http://casparcg.com/builds/CasparCG%20Server/2.1.0/CasparCG%20Server%20f15ba601fe06a7f57512c14c5958cadebf56d970_windows.zip
and
http://casparcg.com/builds/CasparCG%20Server/master/CasparCG%20Server%20aecd9cf02724299b6c23067639e363f1ca032ba1.zip

**Comment by jaskie** [comment]
Finally fixed in d409a07702bdbeb0732c3105971fc9481918ffbd.
