### ISSUE TITLE
Flash templates not working

### ISSUE THREAD

**Issue by Marcinek4** [jaskie/Server#14]
Hi, I'm using the latest release of your CasparCG Server fork for TVPlay. I'm trying to play the crawls, and when TVPlay sends the command to the CasparCG instance, it returns a "flash call failed" error. Adding the template folder to the allowed list (using FlashCfgWriter: https://github.com/didikunz/FlashEOL/files/5696433/FlashCfgWriter.zip) does not work, even though the 2.0.7.1 Flash EOL Hotfix release (and some others) allow the problem to be solved, and so I've been forced to use versions that do not have some of the features of your fork. I have looked to your code and found that the flash_producer.cpp file (https://github.com/jaskie/Server/blob/master/modules/flash/producer/flash_producer.cpp) has not been changed to change file directories to URL's so that they can be supported by the allowed list. Please change it and make a new release so that Flash templates will work without having to change to a different version that supports them. Thanks!
This might be useful: https://github.com/CasparCG/server/issues/1352
Here is the commit with changes to the flash_producter_cpp file that made it possible for me to run flash templates on the 2.0.7.1 build: https://github.com/CasparCG/server/commit/f4879b8ecde2f2b5b6916b73ffe46c304c8f6c64

**Comment by jaskie** [comment]
Thanks for precise instructions, I've prepared the changes, would you be kind and test new .exe for the use case? I just verified that it still works with existing templates.
[casparcg.zip](https://github.com/jaskie/Server/files/12284397/casparcg.zip)
IMHO much simpler, reliable, of better performance - is simply to register the flash .dll with regsvr32 (`DllRegisterServer` Win32 call). It causes the flash works for CasparCG, but not for IE, hence it's not security flaw.

**Comment by jaskie** [comment]
Fixed in commit 3e14f8d94ac6b0e81ee8690877ca84edb09436b2
