### ISSUE TITLE
Cannot change audio_stream_id and video_stream_id 

### ISSUE THREAD

**Issue by mibuhari** [jaskie/Server#2]
I couldn't succeed in running the following command in casparcg
ADD 1 STREAM "udp://127.0.0.1:9250?pkt_size=1316" -vcodec libx264 -tune zerolatency -preset ultrafast -crf 25 -format mpegts -vf scale=302:168 -audio_stream_id 301 -video_stream_id 310

Is the above correct?
The output of ffprobe shows the stream as running with pid 256 (0x100) and 257 (0x101)

Thanks in advance.

**Comment by jaskie** [comment]
No, you have to omit all `-` signs. Available parameters from command line are:
- vcodec,
- acodec,
- separate-key
- vrate,
- arate (both in kbps),
- options (may be in quotation marks),
- pixel-format,
- output-metadata (also may be in quotation marks),
- audio-metadata,
- video-metadata,
- audio_stream_id,
- video_stream_id

So in your case correct command syntax is:
`
ADD 1 STREAM "udp://127.0.0.1:9250?pkt_size=1316" vcodec libx264 audio_stream_id 301 video_stream_id 310 options="preset=ultrafast,tune=zerolatency,crf=25"`

Currently there is no way to freely apply filter, and scaling is available on current release, but limited only to formats defined in CasparCG (PAL, 1080i5000 etc.)
