### ISSUE TITLE
LOOP does not work properly in 7.3b

### ISSUE THREAD

**Issue by martastain** [jaskie/Server#6]
When `PLAY 1-1 somefile LOOP` is called, the file plays only twice and then stops instead playing in an infinite loop. This is a new issue introduced after fixing #5 . 

Tested with many files including the multichannel audio test files I've provided and the old SVT's go1080p50 demo clip.

Layer info command reports this after playback is stopped and numbers do not change:
```xml
<layer>
   <status>playing</status>
   <auto_delta>-1</auto_delta>
   <frame-number>710</frame-number>
   <nb_frames>4294967295</nb_frames>
   <frames-left>4294966586</frames-left>
   <frame-age>121</frame-age>
   <foreground>
      <producer>
         <type>ffmpeg-producer</type>
         <filename>c:\playout\media.dir\16ch.mxf</filename>
         <file-width>1920</file-width>
         <file-height>1080</file-height>
         <file-fps>25</file-fps>
         <file-progressive>false</file-progressive>
         <fps>25</fps>
         <loop>true</loop>
         <nb-frames>4294967295</nb-frames>
         <frame-number>354</frame-number>
      </producer>
   </foreground>
   <background>
      <producer>
         <type>empty-producer</type>
      </producer>
   </background>
   <index>1</index>
</layer>
```

**Comment by jaskie** [comment]
Just fixed, thanks for testing. The hotfix exe is below.
Also noticed, that alpha in separate file is not supported in this fork (but files with embedded alpha works pretty well).
[casparcg.zip](https://github.com/jaskie/Server/files/4380326/casparcg.zip)
