### ISSUE TITLE
Noise audio

### ISSUE THREAD

**Issue by theusmpa** [jaskie/Server#8]
Hello .. Good night!

First I want to thank you for the great work you have done!
I found a problem that seems to have been found and solved at the fork of NKR or in the last official summers of CasparCG, when playing certain clips, I hear small noises as if they were crackling in the audio, this causes me a big problem to put this server into production .
Under the same conditions when using fork v2.1.11_NRK or the official version, this problem does not happen (same media, same hardware).

The noise presented is like the one reported on that [link](https://casparcgforum.org/t/strange-audio-noise-when-playing-videos/2181).
I have not tested changing the BMD drive version for the fact that it worked well on the other server versions.

Do you have any tips on what could be happening? What firmware version do you use on BMD cards in your production?
 
Here I am using Decklink Duo 2 (driver 11.5.1), Windows 10 Pro.

**Comment by jaskie** [comment]
I noticed same effect when was playing videos with mono audio. Due lack of time, I abandoned playing such files, and switched to dual mono files, and it's OK thereafter. If you can confirm that is also your case, let me know. Maybe I should dig deeper...

**Comment by theusmpa** [comment]
Hello!

This is not the case, the problem persists regardless of the number of channels.

I could see that this problem has been fixed in the latest versions of CasparCG, it seems to me to be something related to memory leak in BMD outputs ...

What version of the BMD drive do you use to perform a test?

Thank you.

**Comment by jaskie** [comment]
We are using the CasparCG for years, with different BMD driver version (11.5.1 as well), and besides this mono issue, I never heard such effect. Can you provide me your `casparcg.config` and a sample file to priv (using GDrive or some other)?

**Comment by theusmpa** [comment]
I just did other tests to prepare a file for you to test, but I noticed that in the same file, sometimes it has the flaw and sometimes it doesn't ... I believe it is not related to the media file.

I'm forwarding my configuration file for verification.

What I'm sure is that in the last fork of NRK and in the official this problem does not happen at any time, however they do not get along with manipulating the media to perform the mark in and mark out.
Do you have any future plans to update this fork to the latest version of CasparCG?

The detail of this noise and reproducing 16 audio channels (we are dealing with this [here](https://github.com/jaskie/Server/issues/9)) is preventing me from putting the solution into production.

Again I congratulate you for the great job, I look forward to helping you with these issues.

Thank you!

Matheus

(Note: I changed the file extension to txt just to make it easier to send here.)
[casparcg.config.txt](https://github.com/jaskie/Server/files/4793155/casparcg.config.txt)

**Comment by martastain** [comment]
Can you set the layer mixer volume to 0.9 and check if the problem persists? If I recall correctly, there was a bug in early 2.07 builds and it may be present in 2.06 which caused similar distortions.

**Comment by theusmpa** [comment]
Yes it persists, it is not related to the volume, but to a cadence when the channel is set to 1080i5994 (The audio mixer alerts you to zero samples attached.), I just changed it to 1080p2997 and the problem is gone.

I just researched and found the solution, it is a problem already known from this version that was solved in the later versions, as can be seen [here](https://github.com/CasparCG/server/issues/387).

Could you fix this bug on fork tvPlay?

**Comment by jaskie** [comment]
It seems to be related. I'll try to backport the fix. It may be related to mono audio issue, as it sounds very similar to me.

**Comment by jaskie** [comment]
@theusmpa, would you kindly test [this exe](https://github.com/jaskie/Server/files/4801237/casparcg.zip), if the problem is gone? Just replace the exe file in working CasparCG folder.

**Comment by theusmpa** [comment]
Even the moment was perfect! without any noise!
I will perform more test more I believe it was solved!
Out of curiosity, was the problem related to the discussion above?

Thank you!

**Comment by jaskie** [comment]
Yes, I just backported the fix for discussion you mentioned. The success is yours, definitely. Thanks for reporting and the clue.

**Comment by theusmpa** [comment]
I thank you, I'm happy to be useful in some way.

Thank you.
