### ISSUE TITLE
16 channel audio

### ISSUE THREAD

**Issue by theusmpa** [jaskie/Server#9]
Hello .. Good night!

First I want to thank you for the great work you have done!

I would like to work with 16 audio channels, what would be the valid configuration for that?

I've tried using <channel-layout> passthrue </channel-layout>

Below is my configuration:

`<configuration>
  <log-level>debug</log-level>
  <paths>
    <media-path>media\</media-path>
    <log-path>log\</log-path>
    <data-path>data\</data-path>
    <template-path>templates\</template-path>
    <thumbnails-path>thumbnails\</thumbnails-path>
  </paths>
  <thumbnails>
    <generate-thumbnails>false</generate-thumbnails>
    <width>1024</width>
    <height>576</height>
    <video-grid>2</video-grid>
    <scan-interval-millis>5000</scan-interval-millis>
    <generate-delay-millis>2000</generate-delay-millis>
    <video-mode>720p2500</video-mode>
  </thumbnails>  
  <channels>
    <channel>
      <video-mode>1080i5994</video-mode>
      <channel-layout>passthru</channel-layout>
      <consumers> 
	 <decklink>
            <device>1</device>
            <embedded-audio>true</embedded-audio>
            <channel-layout>passthru</channel-layout>
            <keyer>default</keyer>
            <latency>normal</latency>
            <buffer-depth>4</buffer-depth>
          </decklink>   
            <ndi>
              <name>PGM-UDI</name>
              <blocking>true</blocking>
            </ndi>
      </consumers>
    </channel>  
<channel>
      <video-mode>1080i5994</video-mode>
      <channel-layout>passthru</channel-layout>
      <consumers> 
	 <decklink>
            <device>2</device>
            <embedded-audio>true</embedded-audio>
            <channel-layout>passthru</channel-layout>
            <keyer>default</keyer>
            <latency>normal</latency>
            <buffer-depth>4</buffer-depth>
          </decklink>   
            <ndi>
              <name>PGM-ITU</name>
              <blocking>true</blocking>
            </ndi>
      </consumers>
    </channel>  
<channel>
      <video-mode>1080i5994</video-mode>
      <channel-layout>passthru</channel-layout>
      <consumers> 
	 <decklink>
            <device>3</device>
            <embedded-audio>true</embedded-audio>
            <channel-layout>passthru</channel-layout>
            <keyer>default</keyer>
            <latency>normal</latency>
            <buffer-depth>4</buffer-depth>
          </decklink>   
            <ndi>
              <name>PVW</name>
              <blocking>true</blocking>
            </ndi>
      </consumers>
    </channel>  	
	</channels>
	<controllers>
		<tcp>
			<port>5250</port>
			<protocol>AMCP</protocol>
		</tcp>
	</controllers>
	<osc>
		<default-port>6250</default-port>
	</osc>
</configuration>`

Thank you.

**Comment by jaskie** [comment]
Seems to be nearly perfect, only avoid both consumers to be blocking: decklink is always blocking, and NDI can be blocking (and in this case shouldn't be). The "blocking" consumer gives clock to its channel, what is especially important in NTSC modes.
Is there something that don't work? I personally use the passthru audio channel layout when capture video from decklink input, and it works perfectly. If you want to play more channels from file, remember that CasparCG cannot join audio streams, so file to play must have with single, multi-channel audio stream. I have tested such a playout some time ago, it should work flawlessly. Use i.e. [MediaInfo](https://mediaarea.net/pl/MediaInfo) to check actual file layout.
--- Jurek

**Comment by theusmpa** [comment]
Hello!

My need would be to play MXF files with 16 channels of audio, with this configuration I can't?

What would be the correct configuration for this?

Thank you again!

**Comment by jaskie** [comment]
Just check the files with MediaInfo. Most of MXF files I have seen had bunch (1-8) mono or stereo streams, so only first of them will be played. You can rewrap video track of the files, and re-encode audio with [`amerge`](https://ffmpeg.org/ffmpeg-filters.html#amerge-1) FFmpeg filter. This should be pretty fast, nearly as fast as copying the file.
Refer also to [this](https://trac.ffmpeg.org/wiki/AudioChannelManipulation).

**Comment by theusmpa** [comment]
Good Morning!

See if I understand, are you telling me that if I have an MXF file with 16 channels of audio in mono that fork is able to reproduce the 16 channels on the BMD output?

What would be the proper configuration on the server?

Could you explain to me how to solve this? _"Seems to be nearly perfect, only avoid both consumers to be blocking: decklink is always blocking, and NDI can be blocking (and in this case shouldn't be). The "blocking" consumer gives clock to its channel, what is especially important in NTSC modes."_

Thank you!

**Comment by jaskie** [comment]
1. It will play them all only if the channels are in single stream. In opposite case it will play all channels from first stream only. Be more familiar with stream concept. Use the MediaInfo to check the files.
2. Remove, or change <blocking> parameter of NDI consumer to false.

**Comment by theusmpa** [comment]
OK thank you.

I will do some testing.

Matheus

**Comment by jaskie** [comment]
I have an idea (implemented elsewhere) that would allow to play channels from all audio streams.
Do you want to use the 16-channels with TVPlay, or using another client app? I ask you, because in first case it would be better and easier to convert input files during ingest.

**Comment by theusmpa** [comment]
That! I certainly intend to use the TvPlay client, what would be your idea?

Thank you.

**Comment by jaskie** [comment]
I'm rewraping such files during ingest. Now it works only for dual mono (typically from XDCAM MXF files) -> stereo conversion, but it can be extended. So this is the idea: convert all the files to one-audio-stream files, that will be playable in CasparCG, regardless of version.
Opposite approach is to decode all audio streams, and then merge the audio in CasparCG. But this would be huge change, and probably will not be applied in main CasparCG branch, so it would increase incompatibility with the main release.

**Comment by theusmpa** [comment]
I think that regardless of the form, the final result is achieved.
In my case, I necessarily need to work with the 16 channels and I have already tested it according to your orientation and everything went well.
I was even writing a script to organize these files and already make them available in the CasparCG media folder, but it was going to be a script outside the main application, even though the source of TvPlay, due to lack of knowledge, I don't feel comfortable changing it.
Could you make this option available in your application to reorganize these audios during ingestion?
I would be very happy! :)

Thank you for your attention.

**Comment by jaskie** [comment]
@theusmpa, please, open enhacement request on [TVPlay tracker](https://github.com/jaskie/PlayoutAutomation/issues). I'll look around and try to implement it.
